Repository rarimo/rarime-ios-app, pull requests merged in 2024-09, with the labels that each got.

#91 Add iCloud backup
  Rarime.xcodeproj/project.pbxproj
  Rarime/Code/Constants/Icons.swift
  Rarime/Code/Models/User.swift
  Rarime/Code/Modules/Intro/Views/GetStartedView.swift
  Rarime/Code/Modules/Intro/Views/ImportIdentityView.swift
  Rarime/Code/Modules/Intro/Views/NewIdentityView.swift
  Rarime/Code/Utilities/CloudStorage.swift
  Rarime/Rarime.entitlements
  Rarime/Resources/Assets.xcassets/Icons/Cloud.imageset/Contents.json
  Rarime/Resources/Assets.xcassets/Icons/Cloud.imageset/cloud.svg
  Rarime/Resources/Localizable.xcstrings
Labels: Priority: Medium, Status: Review Required

#95 Handle Download Circuit Connection Error
  Rarime.xcodeproj/project.pbxproj
  Rarime/Code/Managers/InternetConnectionManager.swift
  Rarime/Code/Models/Errors.swift
  Rarime/Code/Modules/App/Views/AppView.swift
  Rarime/Code/Modules/Common/Views/InternetConnectionRequiredView.swift
  Rarime/Code/Modules/ScanPassport/Views/PassportProofView.swift
  Rarime/Code/Modules/ScanPassport/Views/ScanPassportView.swift
  Rarime/Code/RarimeApp.swift
  Rarime/Resources/Localizable.xcstrings
Labels: Priority: High, Status: Accepted, Type: Bug

#94 Add claimable notifications
  Info.plist
  Rarime.xcodeproj/project.pbxproj
  Rarime/Code/DataModels/PushNotification.xcdatamodeld/PushNotification.xcdatamodel/contents
  Rarime/Code/Managers/ConfigManager.swift
  Rarime/Code/Managers/NotificationManager.swift
  Rarime/Code/Models/ClaimableNotificationContent.swift
  Rarime/Code/Models/Points.swift
  Rarime/Code/Models/PushNotificationsRaw.swift
  Rarime/Code/Modules/Home/Views/HomeView.swift
  Rarime/Code/Modules/Notifications/Views/NotificationSheetView.swift
  Rarime/Code/Modules/Notifications/Views/NotificationsView.swift
  Rarime/Code/Modules/Profile/Views/ProfileView.swift
  Rarime/Code/Modules/Rewards/Views/RewardsView.swift
  Rarime/Code/Modules/ScanPassport/ViewModels/PassportViewModel.swift
  Rarime/Resources/Localizable.xcstrings
  Rarime/SupportingFiles/Configs/Development.xcconfig
  Rarime/SupportingFiles/Configs/Production.xcconfig
Labels: Priority: Medium, Status: Review Required, Type: Enhancement
